### ISSUE TITLE
Could not query WANDSLInterfaceConfig1 with action GetInfo

### ISSUE THREAD

**Issue by ikorbln** [blackw1ng/FritzBox-monitor#4]
Hi,

I setup all the needed components, but when i start the script i get the following output:

```
Could not query WANDSLInterfaceConfig1 with action GetInfo
Traceback (most recent call last):
  File "checkfritz.py", line 113, in <module>
    info = readout('WANDSLInterfaceConfig1', 'GetInfo')
  File "checkfritz.py", line 27, in readout
    answer_dict = fc.call_action(module, action)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/fritzconnection.py", line 284, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 259, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 241, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.8/dist-packages/fritzconnection/core/soaper.py", line 164, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzActionError: UPnPError: 
errorCode: 401
errorDescription: Invalid Action
```

When i do this manuel i get this:
```
root@inflgraf:/home/telegraf# fritzconnection -i 192.168.232.254 -S WANDSLInterfaceConfig1

fritzconnection v1.9.1
FRITZ!Box 6591 Cable (kdg) at http://192.168.232.254
FRITZ!OS: 7.29


Servicename:        WANDSLInterfaceConfig1
Actionnames:
                    GetInfo
                    GetStatisticsTotal
                    X_AVM-DE_GetDSLDiagnoseInfo
                    X_AVM-DE_GetDSLInfo
```

So, fritzconnection should work.
And it is a CableBox.
The OS is Ubuntu 20.04 with the latest updates, Python 3.8

**Comment by gbi39** [comment]
Hi,

I have a similar problem like ikorbln.

I have installed and setup all stuff like described. When I run checkfritz.py I get:

----
Could not query DeviceInfo1 with action GetInfo
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fritzconnection/core/soaper.py", line 140, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/checkfritz.py", line 91, in <module>
    deviceinfo = readout('DeviceInfo1', 'GetInfo', 'NewSerialNumber')
  File "/usr/local/bin/checkfritz.py", line 27, in readout
    answer_dict = fc.call_action(module, action)
  File "/usr/local/lib/python3.9/dist-packages/fritzconnection/core/fritzconnection.py", line 284, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.9/dist-packages/fritzconnection/core/soaper.py", line 259, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.9/dist-packages/fritzconnection/core/soaper.py", line 241, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.9/dist-packages/fritzconnection/core/soaper.py", line 150, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Mon, 04 Apr 2022 08:05:01 GMT
----

When I do a "fritzconnection -i 192.168.88.1 -S WANDSLInterfaceConfig1" I get:

----
fritzconnection v1.9.1
FRITZ!Box 7490 at http://192.168.88.1
FRITZ!OS: 7.29


Servicename:        WANDSLInterfaceConfig1
Actionnames:
                    GetInfo
                    GetStatisticsTotal
                    X_AVM-DE_GetDSLDiagnoseInfo
                    X_AVM-DE_GetDSLInfo
----

I have changed the IP address of the FB in checkfritz.py. TR-064 is activated in the FB, the setting of UPnP doesn't matter. I'm doing this is on a recent Debian Bullseye on amd64.

What's going wrong ?

**Comment by gbi39** [comment]
Hi all,
this is only for the records.
If you get such weird messages/exceptions like the ones I had above, double-check the credentials checkfritz.py uses to login to your FB. Using wrong credentials (perhaps with typos in them) are not handled graciously by checkfritz.py. I'm sorry to say this, no insult. But maybe there is some room for improvement
My checkfritz.py runs, but it also consumes a valuable amount of (cpu/ram) resources, on a Raspi 3B+, running it as a telegraf plugin

**Comment by blackw1ng** [comment]
Aloha, for some reason i missed the ticket - the handling of credentials is rather poor, i agree - shame on me, as well as the Fritzconnection. Lemme see what we can do there.

**Comment by DanielHani** [comment]
Hey guys, I figured something out. Even though WANDSLInterfaceConfig1 is offered, it does not work with cable modems.
I fixed this by leaving it out entirely in the checkfritz.py.

For now, it's working and I'm stuck somewhere else. I am going to open a separate issue for that.
